service: tesla-powerwall-scheduler

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  timeout: 30
  environment:
    TESLA_REFRESH_TOKEN: ${env:TESLA_REFRESH_TOKEN}
    TESLA_CLIENT_ID: ${env:TESLA_CLIENT_ID}
    TESLA_CLIENT_SECRET: ${env:TESLA_CLIENT_SECRET}

functions:
  setMidnightReserve:
    handler: handler.handler
    events:
      - schedule:
          rate: cron(0 14 * * ? *) # Midnight AEST
          input:
            reservePercent: 40

  setMorningReserve:
    handler: handler.handler
    events:
      - schedule:
          rate: cron(0 20 * * ? *) # 6am AEST
          input:
            reservePercent: 20

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    platform: node
    exclude:
      - '@aws-sdk/*'
